---
name: Build & Deploy
on: [push, pull_request]

env:
    API_NAME: hello-world


jobs:
    tests-backend:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ['3.8', '3.9', '3.10']
                exclude:
                    - os: macos-latest
                      python-version: '3.8'

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Display Python version
              run: python --version

            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r app/requirements.txt
                  python -m pip install -r requirements-test.txt

            - name: Run test suite
              run: |
                  python -m pytest -v

    build-image:
        needs: [tests-backend]
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - if: ${{ github.actor != 'dependabot[bot]' }}
              name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            - name: Build and push
              id: docker_build_api
              uses: docker/build-push-action@v3
              with:
                  file: Dockerfile
                  # push new image only if on main branch
                  push: ${{ github.ref == 'refs/heads/main' }}
                  tags: |
                      vorphus/${{ env.API_NAME }}:latest
                      vorphus/${{ env.API_NAME }}:${{ github.sha }}

            - name: Image digest
              run: echo ${{ steps.docker_build_api.outputs.digest }}
